# This is the MengServerX configuration file
# 这是MengServerX的配置文件

# Plugin's language (zh and en)
# 插件语言（简体中文'zh'和英文'en'）
Language: 'en'
# Modify the format of messages sent by players
# 修改玩家发送的消息格式
ChatFormat: true
# Whether to enable server welcome
# 是否开启服务器欢迎
JoinTip: true
# Whether to enable player exit reminders
# 是否开启玩家退出提醒
QuitTip: true
# Specifies whether to enable the whitelist
# 是否开启白名单
WhiteList: true
# This feature is KeepInventory for Minecraft
# 是否开启保留物品栏
KeepInventory: false
# Whether to stop Creeper from exploding and destroying terrain
# 是否阻止苦力怕爆炸摧毁地形
AntiCreeperBoom: false
# Whether to turn on Drop Cleanup
# 是否开启掉落物清理
DropCleaner: true
# Dropped items are cleared at regular intervals
# 掉落物清理时常间隔
CleanTime: 600
# Whether to enable the scoreboard
# 是否启用挖掘榜
BreakBoard: true
# Scoreboard name
# 挖掘榜名称
BreakBoardName: "Board"
# Ollama's url
# Ollama地址
OllamaUrl: "http://localhost:11434"
# Ollama model's name
# Ollama 模型名称
OllamaModel: "llama3.1:8b"
# Ollama's character encoding
# Ollama 字符编码
OllamaEncoding: "GBK"
# Prevent unwhitelisted players from logging in prompts
# 阻止无白名单玩家登录提示词
NotAllow: "&c您并没有白名单，请联系服务器管理员"
# A notification sent when the player whitelist is revoked by an administrator
# 玩家白名单被管理员撤销时发送的提示
Repeal: "&c您因违反服务器规则被撤销了白名单"

# A list of player whitelists
# 玩家白名单列表
List: []