name: MengServerX
version: '${project.version}'
main: me.huanmeng.MengServerX
api-version: '1.16'

commands:
  msx_help:
    description: send commands help
  msx_wl_add:
    description: add the whitelist
  msx_wl_remove:
    description: remove the whitelist
  msx_seed:
    description: get world seed
  msx_gm:
    description: set op's game mode
  msx_sn:
    description: send notice
  msx_tp:
    description: teleport to player
  msx_accept:
    description: accept to teleport
  msx_deny:
    description: deny to teleport
  msx_ai:
    description: chat with ai
  msx_ai_reset:
    description: clean history